Travel/Travel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include('travelsapp.urls')),
    path('summernote/', include('django_summernote.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Travel/travelsapp/urls.py
from django.urls import path
from . import views
from django.urls import include
from .views import (
    handleLoginView,
    AdminHomeView,
    signout,
    AdminSectionsView,
    AdminSectionAdd,
    AdminSectionUpdateView,
    AdminSectionDelete,
    AdminSectionStatusUpdate,
    AdminCategoryView,
    AdminCategoryAdd,
    AdminCategoryUpdateView,
    AdminCategoryDelete,
    AdminCategoryStatusUpdate,
    AdminPackageView,
    AdminPackageAdd,
    AjaxGetCategoryView,
    AdminPackageStatusUpdate,
    AdminPackageUpdateView,
    AdminPackageDelete,
    HomeView,
    PackageView,
    PackageDetailsview,
    PackageBookView,
    AdminBookingView,
    AdminBookingDelete,
    AdminBlogView,
    AdminBlogAdd,
    AdminBlogDelete,
    AdminBlogUpdateView,
    AdminBlogStatusUpdate,
    BlogDetailsview,
    BlogView,
    Search

)
# from views import *

app_name = "travelsapp"

urlpatterns = [
    path('', HomeView.as_view(), name='homepage'),
    path('package/<int:pk>/', PackageView.as_view(), name='packages'),
    path('package/packageDetails/<int:pk>',PackageDetailsview.as_view(), name='packageDetails' ),
    path('packages/bookPackage/', PackageBookView.as_view(), name='bookPackage'),
    path('blog', BlogView.as_view(), name='blogPage'),
    path('blog/blogDetails/<int:pk>',BlogDetailsview.as_view(), name='blogDetails' ),
    path('search/', views.Search, name='Search'),




    # admin urls
    path('admin-login/', handleLoginView.as_view(), name='adminLogin'),
    path('med-admin/home', AdminHomeView.as_view(), name='adminHome'),
    path('logout', signout.as_view(), name='logout'),

    # sections urls
    path('med-admin/sections',AdminSectionsView.as_view(), name='adminSectionView' ),
    path('med-admin/sections/add/',AdminSectionAdd.as_view(), name='adminSectionAdd' ),
    path('med-admin/sections/sectionedit/<int:pk>/' ,AdminSectionUpdateView.as_view(), name='adminSectionUpdate' ),
    path('med-admin/delete-section/<int:id>/', views.AdminSectionDelete, name="deleteSection"),
    path('med-admin/update-section-status/<int:id>/', views.AdminSectionStatusUpdate, name="updateSectionStatus"),

    # category urls
    path('med-admin/categories', AdminCategoryView.as_view(), name='adminCategoryView'),
    path('med-admin/category/add/',AdminCategoryAdd.as_view(), name='adminCategoryAdd' ),
    path('med-admin/categories/categoryedit/<int:pk>/' ,AdminCategoryUpdateView.as_view(), name='adminCategoryUpdate' ),
    path('med-admin/update-category-status/<int:id>/', views.AdminCategoryStatusUpdate, name="updateCategoryStatus"),
    path('med-admin/delete-category/<int:id>/', views.AdminCategoryDelete, name="deleteCategory"),

    # packages urls
    path('med-admin/packages', AdminPackageView.as_view(), name='adminPackageView'),
    path('med-admin/package/add/',AdminPackageAdd.as_view(), name='adminPackageAdd' ),
    path('ajax/section-category/', AjaxGetCategoryView.as_view(), name='ajaxGetCategory'),
    path('med-admin/update-package-status/<int:id>/', views.AdminPackageStatusUpdate, name="updateCategoryStatus"),
    path('med-admin/packages/packageedit/<int:pk>/' ,AdminPackageUpdateView.as_view(), name='adminPackageUpdate' ),
    path('med-admin/delete-package/<int:id>/', views.AdminPackageDelete, name="deletePackage"),

    # booking url
    path('med-admin/bookings/', AdminBookingView.as_view(), name='adminBookingView'),
    path('med-admin/bookings/delete-booking/<int:id>/', views.AdminBookingDelete, name="deleteBooking"),


    # blogs urls

    path('med-admin/blogs/', AdminBlogView.as_view(), name='adminBlogView'),
    path('med-admin/blog/add/',AdminBlogAdd.as_view(), name='adminBlogAdd' ),
    path('med-admin/blogs/update-blog-status/<int:id>/', views.AdminBlogStatusUpdate, name="updateBlogStatus"),
    path('med-admin/blogs/blogedit/<int:pk>/' ,AdminBlogUpdateView.as_view(), name='adminBlogUpdate' ),
    path('med-admin/blogs/delete-blog/<int:id>/', views.AdminBlogDelete, name="deleteBlog"),





    


    



    
]

Travel/templates/AdminTemplate/AdminBase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard</title>
    <meta name="csrf-token" content="{{ csrf_token }}">

    <link href="{% static 'adminstatic/dist/css/styles.css' %}" rel="stylesheet" />
    <link href="{% static 'adminstatic/dist/css/bootstrap-toggle.min.css' %}" rel="stylesheet" />
    <link href="{% static 'adminstatic/dist/css/toastr.min.css' %}" rel="stylesheet" />
    <link href="{% static 'adminstatic/dist/css/custom.css' %}" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
</head>

<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="index.html">ADMIN</a><button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button><!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Settings</a><a class="dropdown-item" href="#">Activity Log</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/logout">Logout</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="{% url 'travelsapp:adminHome' %}">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <a class="nav-link" target="_blank" href="{% url 'travelsapp:homepage' %}">
                            <div class="sb-nav-link-icon"><i class="fas fa-scroll"></i></div>
                            Site
                        </a>
                        <div class="sb-sidenav-menu-heading">Catalogue</div>
                        <a class="nav-link" href="{% url 'travelsapp:adminSectionView' %}">
                            <div class="sb-nav-link-icon"><i class="fas fa-list"></i></div>
                            Sections
                        </a>
                        <a class="nav-link" href="{% url 'travelsapp:adminCategoryView' %}">
                            <div class="sb-nav-link-icon"><i class="fas fa-layer-group"></i></div>
                            Category
                        </a>
                        <a class="nav-link" href="{% url 'travelsapp:adminPackageView' %}">
                            <div class="sb-nav-link-icon"><i class="fas fa-plane-departure"></i></div>
                            Packages
                        </a>

                        <div class="sb-sidenav-menu-heading">Costumers</div>
                        <a class="nav-link" href="{% url 'travelsapp:adminBookingView' %}">
                            <div class="sb-nav-link-icon"><i class="fas fa-bookmark"></i></div>
                            Bookings
                        </a>

                        <div class="sb-sidenav-menu-heading">CMS</div>
                        <a class="nav-link" href="{% url 'travelsapp:adminBlogView' %}">
                            <div class="sb-nav-link-icon"><i class="fas fa-blog"></i></div>
                            Blogs
                        </a>
                       





                        
                        <div class="sb-sidenav-menu-heading">Interface</div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-columns"></i>
                            </div>
                            Layouts
                            <div class="sb-sidenav-collapse-arrow">
                                <i class="fas fa-angle-down"></i>
                            </div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="layout-static.html">Static Navigation</a><a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a></nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Pages
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">Authentication
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div></a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="login.html">Login</a><a class="nav-link" href="register.html">Register</a><a class="nav-link" href="password.html">Forgot Password</a></nav>
                                </div>
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">Error
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div></a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="401.html">401 Page</a><a class="nav-link" href="404.html">404 Page</a><a class="nav-link" href="500.html">500 Page</a></nav>
                                </div>
                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading">Addons</div>
                        <a class="nav-link" href="charts.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Charts
                        </a><a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Tables
                        </a>
                    </div>
                </div>
                <!-- <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div> -->
            </nav>
        </div>
        {% block content %}
        {% endblock %}

    </div>
    <footer class="py-4 bg-light mt-auto">
        <div class="container-fluid">
            <div class="d-flex align-items-center justify-content-between small">
                <div class="text-muted">Copyright &copy; Your Website 2019</div>
                <div>
                    <a href="#">Privacy Policy</a>
                    &middot;
                    <a href="#">Terms &amp; Conditions</a>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'adminstatic/dist/js/scripts.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'adminstatic/dist/assets/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'adminstatic/dist/assets/demo/chart-bar-demo.js' %}"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'adminstatic/dist/assets/demo/datatables-demo.js' %}"></script>
    <script src="{% static 'adminstatic/dist/js/toastr.min.js' %}"></script>
    <script src="{% static 'adminstatic/dist/js/sweetalert2.all.min.js' %}"></script>    
    <script src="{% static 'adminstatic/dist/js/bootstrap-toggle.min.js' %}"></script>    
    <script src="{% static 'adminstatic/dist/js/main.js' %}"></script>

    <script>
        toastr.options = {
            "closeButton": true,
            "progressBar": true,
        }
    </script>
    {% if messages %}
    {% for message in messages %}
    {% if message.tags == 'success'%}
    <script>
        toastr.success('{{ message }}', 'Success !')
    </script>{% endif %}
    {% if message.tags == 'error'%}
    <script>
        toastr.error('{{ message }}', 'Error !')
    </script>{% endif %}
    {% endfor %}
    {% endif %}
</body>

</html>

Travel/templates/AdminTemplate/AdminLogin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Tours-Login</title>
    <link href="{% static 'adminstatic/dist/css/styles.css' %}" rel="stylesheet" />
    <link href="{% static 'adminstatic/dist/css/custom.css' %}" rel="stylesheet" />
    <link href="{% static 'adminstatic/dist/css/toastr.min.css' %}" rel="stylesheet" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
</head>

<body class="" style="background-color: #116466;">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-5">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header">
                                    <h3 class="text-center font-weight-light my-4 login-header">Admin Login</h3>
                                </div>
                                <div class="card-body">
                                    <form method="POST" action="{% url 'travelsapp:adminLogin' %}">
                                        {% csrf_token %}
                                        {{ form }}
                                        <!-- <div class="form-group">
                                            <label class="small mb-1" for="username">Email</label>
                                            <input class="form-control py-4" name="username" id="username" type="text" placeholder="Enter email address" />
                                        </div>
                                        <div class="form-group">
                                            <label class="small mb-1" for="password">Password</label>
                                            <input class="form-control py-4" name="password" id="password" type="password" placeholder="Enter password" />
                                        </div>-->
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox"><input class="custom-control-input" id="rememberPasswordCheck" type="checkbox" />
                                                <label class="custom-control-label" for="rememberPasswordCheck">Remember password</label>
                                            </div>
                                        </div>
                                        <div class="form-group mt-4 mb-0">
                                            <button type="submit" class="btn btn-block btn-outline-success">Login</button>
                                            <a class="small" href="password.html">Forgot Password?</a>
                                        </div>
                                    </form>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>

        <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'adminstatic/dist/js/scripts.js' %}"></script>
        <script src="{% static 'adminstatic/dist/js/toastr.min.js' %}"></script>
        <script>
            toastr.options = {
                "closeButton": true,
                "progressBar": true,
            }
        </script>
        {% if messages %}
        {% for message in messages %}
        {% if message.tags == 'success'%}<script>toastr.success ('{{ message }}','Success !')</script>{% endif %}
        {% if message.tags == 'error'%}<script>toastr.error ('{{ message }}', 'Error !')</script>{% endif %}
        {% endfor %}

        {% endif %}

</body>

</html>