Travel/Travel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include('travelsapp.urls')),
    path('summernote/', include('django_summernote.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Travel/travelsapp/urls.py
from django.urls import path
from . import views
from django.urls import include
from .views import (
    handleLoginView,
    AdminHomeView,
    signout,
    AdminSectionsView,
    AdminSectionAdd,
    AdminSectionUpdateView,
    AdminSectionDelete,
    AdminSectionStatusUpdate,
    AdminCategoryView,
    AdminCategoryAdd,
    AdminCategoryUpdateView,
    AdminCategoryDelete,
    AdminCategoryStatusUpdate,
    AdminPackageView,
    AdminPackageAdd,
    AjaxGetCategoryView,
    AdminPackageStatusUpdate,
    AdminPackageUpdateView,
    AdminPackageDelete,
    HomeView,
    PackageView,
    PackageDetailsview,
    PackageBookView,
    AdminBookingView,
    AdminBookingDelete,
    AdminBlogView,
    AdminBlogAdd,
    AdminBlogDelete,
    AdminBlogUpdateView,
    AdminBlogStatusUpdate,
    BlogDetailsview,
    BlogView,
    Search

)
# from views import *

app_name = "travelsapp"

urlpatterns = [
    path('', HomeView.as_view(), name='homepage'),
    path('package/<int:pk>/', PackageView.as_view(), name='packages'),
    path('package/packageDetails/<int:pk>',PackageDetailsview.as_view(), name='packageDetails' ),
    path('packages/bookPackage/', PackageBookView.as_view(), name='bookPackage'),
    path('blog', BlogView.as_view(), name='blogPage'),
    path('blog/blogDetails/<int:pk>',BlogDetailsview.as_view(), name='blogDetails' ),
    path('search/', views.Search, name='Search'),




    # admin urls
    path('admin-login/', handleLoginView.as_view(), name='adminLogin'),
    path('med-admin/home', AdminHomeView.as_view(), name='adminHome'),
    path('logout', signout.as_view(), name='logout'),

    # sections urls
    path('med-admin/sections',AdminSectionsView.as_view(), name='adminSectionView' ),
    path('med-admin/sections/add/',AdminSectionAdd.as_view(), name='adminSectionAdd' ),
    path('med-admin/sections/sectionedit/<int:pk>/' ,AdminSectionUpdateView.as_view(), name='adminSectionUpdate' ),
    path('med-admin/delete-section/<int:id>/', views.AdminSectionDelete, name="deleteSection"),
    path('med-admin/update-section-status/<int:id>/', views.AdminSectionStatusUpdate, name="updateSectionStatus"),

    # category urls
    path('med-admin/categories', AdminCategoryView.as_view(), name='adminCategoryView'),
    path('med-admin/category/add/',AdminCategoryAdd.as_view(), name='adminCategoryAdd' ),
    path('med-admin/categories/categoryedit/<int:pk>/' ,AdminCategoryUpdateView.as_view(), name='adminCategoryUpdate' ),
    path('med-admin/update-category-status/<int:id>/', views.AdminCategoryStatusUpdate, name="updateCategoryStatus"),
    path('med-admin/delete-category/<int:id>/', views.AdminCategoryDelete, name="deleteCategory"),

    # packages urls
    path('med-admin/packages', AdminPackageView.as_view(), name='adminPackageView'),
    path('med-admin/package/add/',AdminPackageAdd.as_view(), name='adminPackageAdd' ),
    path('ajax/section-category/', AjaxGetCategoryView.as_view(), name='ajaxGetCategory'),
    path('med-admin/update-package-status/<int:id>/', views.AdminPackageStatusUpdate, name="updateCategoryStatus"),
    path('med-admin/packages/packageedit/<int:pk>/' ,AdminPackageUpdateView.as_view(), name='adminPackageUpdate' ),
    path('med-admin/delete-package/<int:id>/', views.AdminPackageDelete, name="deletePackage"),

    # booking url
    path('med-admin/bookings/', AdminBookingView.as_view(), name='adminBookingView'),
    path('med-admin/bookings/delete-booking/<int:id>/', views.AdminBookingDelete, name="deleteBooking"),


    # blogs urls

    path('med-admin/blogs/', AdminBlogView.as_view(), name='adminBlogView'),
    path('med-admin/blog/add/',AdminBlogAdd.as_view(), name='adminBlogAdd' ),
    path('med-admin/blogs/update-blog-status/<int:id>/', views.AdminBlogStatusUpdate, name="updateBlogStatus"),
    path('med-admin/blogs/blogedit/<int:pk>/' ,AdminBlogUpdateView.as_view(), name='adminBlogUpdate' ),
    path('med-admin/blogs/delete-blog/<int:id>/', views.AdminBlogDelete, name="deleteBlog"),





    


    



    
]

Travel/templates/AdminTemplate/BookingsTemplate/ListBookings.html
{% extends 'admintemplate/adminBase.html' %}

{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid">
            <h2 class="mt-4">BOOKINGS</h2>
            <ol class="breadcrumb mb-2">
                <li class="breadcrumb-item "><a href="{% url 'travelsapp:adminHome' %}">Dashboard</a> </li>
                <li class="breadcrumb-item active">Booking</li>
            </ol>
            <div class="">
                <!-- <a class="btn btn-outline-success my-2 " href="{% url 'travelsapp:adminCategoryAdd' %}"><i class="fa fa-plus"></i> &nbsp; Add Category</a> -->
            </div>
            <div class="card mb-4">
                <div class="card-header"><i class="fas fa-table mr-1"></i>Category List</div>
                <div class="card-body">
                    <div class="table-responsive">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>Full Name</th>
                                        <th>Email </th>
                                        <th>Phone</th>
                                        <th>Package Name</th>
                                        <th>Action</th>

                                    </tr>
                                </thead>

                                <tbody>
                                    {% for booking in bookingsList %}
                                    <tr>
                                        <td>{{booking.fullname}}</td>
                                        <td>{{booking.email}}</td>
                                        <td>{{booking.phone}}</td>
                                        <td>{{booking.package_name}}</td>
                                        <td>
                                            <a ype="button" data-toggle="modal" data-target="#exampleModal-{{booking.id}}" class="btn btn-outline-primary my-1"><span class="far fa-eye"></span></a>
                                            <a href="" class="btn btn-outline-info my-1"><span class="far fa-edit"></span></a>
                                            <a class="btn btn-outline-danger my-1 deleteRecord" rel="{{booking.id}}" rel1="delete-booking" href="javascript:"><span class="far fa-trash-alt"></span></a>
                                        </td>

                                    </tr>
                                    <!-- Button trigger modal -->

                                    <!-- Modal -->
                                    <div class="modal fade" id="exampleModal-{{booking.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">{{booking.fullname}}'\s Booking</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <div class="row">
                                                        <div class="col-md-4">
                                                            Package Name: <br>
                                                            Email: <br>
                                                            Address: <br>
                                                            Phone: <br>
                                                            Number Of Person: <br>
                                                            Date: <br>
                                                            Pickup Details: <br>
                                                            Message: <br>


                                                        </div>
                                                        <div class="col-md-8">
                                                            {{booking.package_name}} <br>
                                                            {{booking.email}} <br>
                                                            {{booking.address}} <br>
                                                            {{booking.phone}} <br>
                                                            {{booking.count}} <br>
                                                            {{booking.date}} <br>
                                                            {{booking.pickup}} <br>
                                                            {{booking.message}} <br>

                                                            <br>


                                                        </div>
                                                    </div>

                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

</div>

{% endblock %}